/*
 * 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.util.Scanner;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import vm252simulation.VM252Model;
import vm252simulation.VM252View;

import java.io.File;
import java.io.IOException;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;


/**
 * 
 * @author : Abigail Wood, Sabina Dahal, and Supreme Paudel
 */

class accumulatorPrinter extends VM252View {
         
    private final VM252Model myModel;
    
    public accumulatorPrinter(VM252Model model)
    {       
        myModel = model;       
        }
    
    @Override
    public void updateAccumulator()
    {       
        System.out.println("accumulators is now " + myModel.accumulator()); 
        DebugFrame.accumulator_display.setText(""+myModel.accumulator());
        // to do : to update the gui value
        }
    
    public void setAccumulator(int value){
        
        myModel.setAccumulator(value);
    
    }
    }

class ProgramCounterPrinter extends VM252View
    {
    
    private final VM252Model myModel;
    
    public ProgramCounterPrinter(VM252Model model)
    {        
        myModel = model;        
        }
    
    @Override
    public void updateProgramCounter()
    {        
        System.out.println("program counter is now " + myModel.programCounter());  
        DebugFrame.count_diplay.setText(""+myModel.programCounter());
        } 
    
    
    public void setProgramCounter(int value){
        
        myModel.setProgramCounter(value);
    
    }
    
    }

class MemoryBytePrinter extends VM252View
    {
    
    private final VM252Model myModel;
    
    public MemoryBytePrinter(VM252Model model)
    {        
        myModel = model;        
        }
    
   @Override
    public void updateMemory(int address)
    {        
        System.out.printf("memory byte at address %d is now %02x\n", address, myModel.memoryByte(address));        
      
        String formattedString = String.format("memory byte at address %d is now %02x\n", address, myModel.memoryByte(address));
        DebugFrame.input_code_area.append(formattedString);       

        }

    }

class StopAnnouncer extends VM252View
    {
    
    private final VM252Model myModel;
    
    public StopAnnouncer(VM252Model model)
    {        
        myModel = model;        
        }
    
    @Override
    public void updateStoppedStatus()
    {        
        // TO DO : UPDATE GUI AFTER PROGRAM HAS ENDED
        System.out.printf(
            "machine stops with accumulator %d and program counter %d\n",
                myModel.accumulator(),
                myModel.programCounter()
            );        
        }
    }

public class DebugFrame extends javax.swing.JFrame {

    final JFileChooser fileChooser = new JFileChooser();
    String objFileName = "";
    static guiController simulator;
    static accumulatorPrinter accumulatorPrinterObject;
    static ProgramCounterPrinter programCounterPrinterObject;
    static String instruction_to_be_executed;
    VM252Model simulatedMachine;
    /**
     * Creates new form DebugFrame
     */
    public DebugFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        Upper_Panel = new javax.swing.JPanel();
        selectFile = new javax.swing.JButton();
        file_Selected = new javax.swing.JTextField();
        Help = new javax.swing.JButton();
        Button_Panel = new javax.swing.JPanel();
        Start = new javax.swing.JButton();
        Pause = new javax.swing.JButton();
        next_Line = new javax.swing.JButton();
        executeAgain = new javax.swing.JButton();
        Stop = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        adjust_Speed = new javax.swing.JComboBox<>();
        Middle_Panel = new javax.swing.JPanel();
        Middle_West = new javax.swing.JPanel();
        Program_Counter = new javax.swing.JLabel();
        count_diplay = new javax.swing.JTextField();
        Middle_Center = new javax.swing.JPanel();
        accumulator = new javax.swing.JLabel();
        accumulator_display = new javax.swing.JTextField();
        Middle_East = new javax.swing.JPanel();
        next_Instruction = new javax.swing.JLabel();
        instruction_Display = new javax.swing.JTextField();
        Bottom_West = new javax.swing.JPanel();
        input_code_scroll = new javax.swing.JScrollPane();
        input_code_area = new javax.swing.JTextArea();
        Bottom_East = new javax.swing.JPanel();
        Top_Bottom_East = new javax.swing.JPanel();
        input_scroll = new javax.swing.JScrollPane();
        enter_input = new javax.swing.JTextArea();
        output_scroll = new javax.swing.JScrollPane();
        output_display = new javax.swing.JTextArea();
        Input_Value = new javax.swing.JLabel();
        Output_Value = new javax.swing.JLabel();
        Center_Bottom_East = new javax.swing.JPanel();
        memory_options_one = new javax.swing.JComboBox<>();
        memory_display_scroll_one = new javax.swing.JScrollPane();
        memory_display_one = new javax.swing.JTextArea();
        Last_Bottom_East = new javax.swing.JPanel();
        memory_options_two = new javax.swing.JComboBox<>();
        memory_display_scroll_two = new javax.swing.JScrollPane();
        memory_display_two = new javax.swing.JTextArea();

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        Upper_Panel.setName("Upper_Panel"); // NOI18N

        selectFile.setText("Select File");
        selectFile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        selectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileActionPerformed(evt);
            }
        });

        file_Selected.setEditable(false);
        file_Selected.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        file_Selected.setText("No file selected");
        file_Selected.setAutoscrolls(false);
        file_Selected.setBorder(null);
        file_Selected.setFocusable(false);
        file_Selected.setOpaque(true);
        file_Selected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                file_SelectedActionPerformed(evt);
            }
        });

        Help.setLabel("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });

        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        Pause.setActionCommand("Pause");
        Pause.setLabel("Pause");

        next_Line.setText("Next line");
        next_Line.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt){
                NextActionPerformed(evt);
            }
        });

        executeAgain.setText("Again");
        executeAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeAgainActionPerformed(evt);
            }
        });
       
        
        
        

        Stop.setText("Stop");

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        adjust_Speed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Speed", "Speed x1.5", "Speed x2" }));

        javax.swing.GroupLayout Button_PanelLayout = new javax.swing.GroupLayout(Button_Panel);
        Button_Panel.setLayout(Button_PanelLayout);
        Button_PanelLayout.setHorizontalGroup(
            Button_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Start)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pause)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(next_Line)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(executeAgain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Stop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adjust_Speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Button_PanelLayout.setVerticalGroup(
            Button_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Button_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Start)
                    .addComponent(Pause)
                    .addComponent(next_Line)
                    .addComponent(executeAgain)
                    .addComponent(Stop)
                    .addComponent(Save)
                    .addComponent(adjust_Speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Upper_PanelLayout = new javax.swing.GroupLayout(Upper_Panel);
        Upper_Panel.setLayout(Upper_PanelLayout);
        Upper_PanelLayout.setHorizontalGroup(
            Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Upper_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Upper_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Upper_PanelLayout.createSequentialGroup()
                        .addComponent(selectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Help))
                    .addGroup(Upper_PanelLayout.createSequentialGroup()
                        .addComponent(file_Selected, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Upper_PanelLayout.setVerticalGroup(
            Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Upper_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Help, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(file_Selected, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(Button_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        file_Selected.getAccessibleContext().setAccessibleParent(selectFile);

        Middle_West.setBackground(new java.awt.Color(153, 153, 153));
        Middle_West.setToolTipText("");
        Middle_West.setPreferredSize(new java.awt.Dimension(168, 102));

        Program_Counter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Program_Counter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Program_Counter.setText("Count");

        count_diplay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        count_diplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        count_diplay.setText("0");
        count_diplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count_diplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Middle_WestLayout = new javax.swing.GroupLayout(Middle_West);
        Middle_West.setLayout(Middle_WestLayout);
        Middle_WestLayout.setHorizontalGroup(
            Middle_WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Middle_WestLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(Middle_WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Program_Counter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(count_diplay))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        Middle_WestLayout.setVerticalGroup(
            Middle_WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Middle_WestLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Program_Counter, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(count_diplay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Middle_Center.setBackground(new java.awt.Color(153, 153, 153));
        Middle_Center.setPreferredSize(new java.awt.Dimension(168, 102));

        accumulator.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accumulator.setText("ACC");

        accumulator_display.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accumulator_display.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        accumulator_display.setText("0");
        accumulator_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccumulatorChangeActionPerfomed(evt);
            }
        });
        
        javax.swing.GroupLayout Middle_CenterLayout = new javax.swing.GroupLayout(Middle_Center);
        Middle_Center.setLayout(Middle_CenterLayout);
        Middle_CenterLayout.setHorizontalGroup(
            Middle_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Middle_CenterLayout.createSequentialGroup()
                .addGroup(Middle_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Middle_CenterLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(accumulator_display, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Middle_CenterLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(accumulator, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        Middle_CenterLayout.setVerticalGroup(
            Middle_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Middle_CenterLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(accumulator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accumulator_display, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Middle_East.setBackground(new java.awt.Color(153, 153, 153));

        next_Instruction.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        next_Instruction.setText("Next Instruction");

        instruction_Display.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        instruction_Display.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        instruction_Display.setText("g#h");

        javax.swing.GroupLayout Middle_EastLayout = new javax.swing.GroupLayout(Middle_East);
        Middle_East.setLayout(Middle_EastLayout);
        Middle_EastLayout.setHorizontalGroup(
            Middle_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Middle_EastLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(Middle_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(instruction_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next_Instruction))
                .addGap(18, 18, 18))
        );
        Middle_EastLayout.setVerticalGroup(
            Middle_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Middle_EastLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(next_Instruction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instruction_Display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout Middle_PanelLayout = new javax.swing.GroupLayout(Middle_Panel);
        Middle_Panel.setLayout(Middle_PanelLayout);
        Middle_PanelLayout.setHorizontalGroup(
            Middle_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Middle_PanelLayout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(Middle_Center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(Middle_West, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(Middle_East, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        Middle_PanelLayout.setVerticalGroup(
            Middle_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Middle_West, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
            .addComponent(Middle_East, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Middle_Center, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );

        input_code_area.setColumns(20);
        input_code_area.setRows(5);
        input_code_scroll.setViewportView(input_code_area);
        input_code_area.getAccessibleContext().setAccessibleParent(Bottom_West);

        javax.swing.GroupLayout Bottom_WestLayout = new javax.swing.GroupLayout(Bottom_West);
        Bottom_West.setLayout(Bottom_WestLayout);
        Bottom_WestLayout.setHorizontalGroup(
            Bottom_WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Bottom_WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Bottom_WestLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_code_scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        Bottom_WestLayout.setVerticalGroup(
            Bottom_WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(Bottom_WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Bottom_WestLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(input_code_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(90, Short.MAX_VALUE)))
        );

        Bottom_East.setBackground(new java.awt.Color(153, 153, 153));

        Top_Bottom_East.setBackground(new java.awt.Color(153, 153, 153));

        input_scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        enter_input.setColumns(20);
        enter_input.setRows(5);
        input_scroll.setViewportView(enter_input);
        enter_input.getAccessibleContext().setAccessibleParent(Bottom_West);

        output_scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        output_display.setColumns(20);
        output_display.setRows(5);
        output_scroll.setViewportView(output_display);

        Input_Value.setBackground(new java.awt.Color(153, 153, 153));
        Input_Value.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Input_Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Input_Value.setText("Input");
        Input_Value.setOpaque(true);

        Output_Value.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Output_Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Output_Value.setText("Output");

        javax.swing.GroupLayout Top_Bottom_EastLayout = new javax.swing.GroupLayout(Top_Bottom_East);
        Top_Bottom_East.setLayout(Top_Bottom_EastLayout);
        Top_Bottom_EastLayout.setHorizontalGroup(
            Top_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Top_Bottom_EastLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Top_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_scroll)
                    .addComponent(Input_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(Top_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(output_scroll)
                    .addComponent(Output_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        Top_Bottom_EastLayout.setVerticalGroup(
            Top_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Top_Bottom_EastLayout.createSequentialGroup()
                .addGroup(Top_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Input_Value)
                    .addGroup(Top_Bottom_EastLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Output_Value)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Top_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Top_Bottom_EastLayout.createSequentialGroup()
                        .addComponent(output_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        Center_Bottom_East.setBackground(new java.awt.Color(153, 153, 153));

        memory_options_one.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Object code as bytes in Hex", "Object code as 2 byte data in Hex", "Object code as instructions-data and labels", "Edit" }));
        memory_options_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memory_options_oneActionPerformed(evt);
            }
        });

        memory_display_one.setEditable(false);
        memory_display_one.setColumns(20);
        memory_display_one.setRows(5);
        memory_display_scroll_one.setViewportView(memory_display_one);

        javax.swing.GroupLayout Center_Bottom_EastLayout = new javax.swing.GroupLayout(Center_Bottom_East);
        Center_Bottom_East.setLayout(Center_Bottom_EastLayout);
        Center_Bottom_EastLayout.setHorizontalGroup(
            Center_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Center_Bottom_EastLayout.createSequentialGroup()
                .addGroup(Center_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memory_display_scroll_one)
                    .addComponent(memory_options_one, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Center_Bottom_EastLayout.setVerticalGroup(
            Center_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Center_Bottom_EastLayout.createSequentialGroup()
                .addComponent(memory_options_one, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(memory_display_scroll_one, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        Last_Bottom_East.setBackground(new java.awt.Color(153, 153, 153));

        memory_options_two.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Object code as bytes in Hex", "Object code as 2 byte data in Hex", "Object code as instructions-data and labels", "Edit" }));
        memory_options_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memory_options_twoActionPerformed(evt);
            }
        });

        memory_display_two.setEditable(false);
        memory_display_two.setColumns(20);
        memory_display_two.setRows(5);
        memory_display_scroll_two.setViewportView(memory_display_two);

        javax.swing.GroupLayout Last_Bottom_EastLayout = new javax.swing.GroupLayout(Last_Bottom_East);
        Last_Bottom_East.setLayout(Last_Bottom_EastLayout);
        Last_Bottom_EastLayout.setHorizontalGroup(
            Last_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Last_Bottom_EastLayout.createSequentialGroup()
                .addGroup(Last_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memory_options_two, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(memory_display_scroll_two))
                .addContainerGap())
        );
        Last_Bottom_EastLayout.setVerticalGroup(
            Last_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Last_Bottom_EastLayout.createSequentialGroup()
                .addComponent(memory_options_two, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(memory_display_scroll_two, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Bottom_EastLayout = new javax.swing.GroupLayout(Bottom_East);
        Bottom_East.setLayout(Bottom_EastLayout);
        Bottom_EastLayout.setHorizontalGroup(
            Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bottom_EastLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Bottom_EastLayout.createSequentialGroup()
                        .addComponent(Top_Bottom_East, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(Center_Bottom_East, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Last_Bottom_East, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Bottom_EastLayout.setVerticalGroup(
            Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bottom_EastLayout.createSequentialGroup()
                .addComponent(Top_Bottom_East, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Center_Bottom_East, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Last_Bottom_East, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Bottom_West, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(Bottom_East, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Upper_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Middle_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Upper_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Middle_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bottom_West, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bottom_East, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void file_SelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_SelectedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_file_SelectedActionPerformed

    private void memory_options_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memory_options_oneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memory_options_oneActionPerformed

    private void memory_options_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memory_options_twoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memory_options_twoActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_StartActionPerformed
        try {
            System.out.println(file_Selected.getText());
            if (file_Selected.getText().equals("No file selected")){
            JOptionPane.showMessageDialog(this, "Select a file first");
            } else {
            System.out.println("Next instruction for file named"+ objFileName);
            // TO DO what to pass here , not sure
            String input_value = accumulator_display.getText();
            Scanner scanner_object = new Scanner(input_value);
            // TO DO what to pass here , not sure
            simulator.loadAndRun(objFileName, scanner_object, System.out, "next");
        }
    }
        catch (IOException e){
    System.out.println("IO Exception");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_StartActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_StartActionPerformed
        try {
            System.out.println(file_Selected.getText());
        if (file_Selected.getText().equals("No file selected")){
            JOptionPane.showMessageDialog(this, "Select a file first");
        } else {
            System.out.println("Running file named"+ objFileName);
            String input_value = accumulator_display.getText();
            Scanner scanner_object = new Scanner(input_value);
            // TO DO what to pass here , not sure
            simulator.loadAndRun(objFileName, scanner_object, System.out, "run");

        }}
        catch (IOException e){
    System.out.println("IO Exception");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_StartActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelpActionPerformed

    private void AccumulatorChangeActionPerfomed(java.awt.event.ActionEvent evt){
        String new_value = accumulator_display.getText();
        accumulatorPrinterObject.setAccumulator(Integer.parseInt(new_value));
    }
    
    private void create_simulation_machine(){

    VM252Model simulatedMachine = new VM252Model();
    accumulatorPrinterObject = new accumulatorPrinter(simulatedMachine);
    programCounterPrinterObject = new ProgramCounterPrinter(simulatedMachine);
    simulatedMachine.attach(accumulatorPrinterObject);
    simulatedMachine.attach(programCounterPrinterObject);
    simulatedMachine.attach(new MemoryBytePrinter(simulatedMachine));
    simulatedMachine.attach(new StopAnnouncer(simulatedMachine));

    simulator = new guiController(simulatedMachine);
    }

    private void selectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileActionPerformed

        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(fileChooser);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String selectedFileName = selectedFile.getName();
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
            if (selectedFileName.endsWith(".vm252obj")) 
            {
             // System.out.println("valid file");
            file_Selected.setText(selectedFile.getName());
            objFileName = selectedFile.getAbsolutePath();
            accumulator_display.setText("0");
            count_diplay.setText("0");
            create_simulation_machine();
        }
            else {
                //System.out.print("Invalid file");
            JOptionPane.showMessageDialog(this, "File must end with .vm252obj");  
            objFileName = "";
        }
        } else {
        file_Selected.setText("No file selected");
                }

        
    }
    private void executeAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeAgainActionPerformed
         count_diplay.setText("0");
         accumulator_display.setText("0");
         instruction_Display.setText("");
         DebugFrame.input_code_area.setText(" ");
         create_simulation_machine();
       
        
    }//GEN-LAST:event_executeAgainActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
       

        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    private void count_diplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_diplayActionPerformed
        // TODO add your handling code here:
        String new_value = count_diplay.getText();
        programCounterPrinterObject.setProgramCounter(Integer.parseInt(new_value));
    
    }//GEN-LAST:event_count_diplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DebugFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DebugFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DebugFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DebugFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DebugFrame().setVisible(true);
            }
        });


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom_East;
    private javax.swing.JPanel Bottom_West;
    private javax.swing.JPanel Button_Panel;
    private javax.swing.JPanel Center_Bottom_East;
    private javax.swing.JButton Help;
    private javax.swing.JLabel Input_Value;
    private javax.swing.JPanel Last_Bottom_East;
    private javax.swing.JPanel Middle_Center;
    private javax.swing.JPanel Middle_East;
    private javax.swing.JPanel Middle_Panel;
    private javax.swing.JPanel Middle_West;
    private javax.swing.JLabel Output_Value;
    private javax.swing.JButton Pause;
    private javax.swing.JLabel Program_Counter;
    private javax.swing.JButton Save;
    private javax.swing.JButton Start;
    private javax.swing.JButton Stop;
    private javax.swing.JPanel Top_Bottom_East;
    private javax.swing.JPanel Upper_Panel;
    private javax.swing.JLabel accumulator;
    public static javax.swing.JTextField accumulator_display;
    private javax.swing.JComboBox<String> adjust_Speed;
    public static javax.swing.JTextField count_diplay;
    private javax.swing.JTextArea enter_input;
    private javax.swing.JButton executeAgain;
    private javax.swing.JTextField file_Selected;
    public static  javax.swing.JTextArea input_code_area;
    private javax.swing.JScrollPane input_code_scroll;
    private javax.swing.JScrollPane input_scroll;
    public static javax.swing.JTextField instruction_Display;
    private javax.swing.JComboBox<String> jComboBox3;
    public static javax.swing.JTextArea memory_display_one;
    public static javax.swing.JScrollPane memory_display_scroll_one;
    public static javax.swing.JScrollPane memory_display_scroll_two;
    private javax.swing.JTextArea memory_display_two;
    public static javax.swing.JComboBox<String> memory_options_one;
    private javax.swing.JComboBox<String> memory_options_two;
    private javax.swing.JLabel next_Instruction;
    private javax.swing.JButton next_Line;
    public static javax.swing.JTextArea output_display;
    private javax.swing.JScrollPane output_scroll;
    private javax.swing.JButton selectFile;
    // End of variables declaration//GEN-END:variables

    private Scanner Scanner(String input_value) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


}
