package demonstration;


import java.io.IOException;
import java.util.Scanner;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import vm252simulation.VM252Model;
import vm252simulation.VM252View;
import vm252utilities.VM252Utilities;


class AccumulatorPrinter extends VM252View
{
    
    private final VM252Model myModel;
    
    public AccumulatorPrinter(VM252Model model)
    {       
        myModel = model;       
        }
    
    @Override
    public void updateAccumulator()
    {       
        System.out.println("accumulator is now " + myModel.accumulator());        
        }
    
    }


class ProgramCounterPrinter extends VM252View
{
    
    private final VM252Model myModel;
    
    public ProgramCounterPrinter(VM252Model model)
    {        
        myModel = model;        
        }
    
    @Override
    public void updateProgramCounter()
    {        
        System.out.println("program counter is now " + myModel.programCounter());        
        }
    
    }


class MemoryBytePrinter extends VM252View
{
    
    private final VM252Model myModel;
    
    public MemoryBytePrinter(VM252Model model)
    {        
        myModel = model;        
        }
    
    @Override
    public void updateMemory(int address)
    {        
        System.out.printf("memory byte at address %d is now %02x\n", address, myModel.memoryByte(address));        
        }
    
    }


class StopAnnouncer extends VM252View
{
    
    private final VM252Model myModel;
    
    public StopAnnouncer(VM252Model model)
    {        
        myModel = model;        
        }
    
    @Override
    public void updateStoppedStatus()
    {        
        System.out.printf(
            "machine stops with accumulator %d and program counter %d\n",
                myModel.accumulator(),
                myModel.programCounter()
            );        
        }
    
    }


public class Demonstration
{

    public static void main(String [ ] commandLineArguments) throws IOException
    {public class DebugFrame extends javax.swing.JFrame {

        /**
         * Creates new form DebugFrame
         */
        public DebugFrame() {
            initComponents();
        }
    
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
    
            jComboBox3 = new javax.swing.JComboBox<>();
            Upper_Panel = new javax.swing.JPanel();
            selectFile = new javax.swing.JButton();
            file_Selected = new javax.swing.JTextField();
            Help = new javax.swing.JButton();
            jPanel2 = new javax.swing.JPanel();
            Start = new javax.swing.JButton();
            Pause = new javax.swing.JButton();
            next_Line = new javax.swing.JButton();
            executeAgain = new javax.swing.JButton();
            Stop = new javax.swing.JButton();
            Save = new javax.swing.JButton();
            adjust_Speed = new javax.swing.JComboBox<>();
            Middle_Panel = new javax.swing.JPanel();
            Middle_West = new javax.swing.JPanel();
            Program_Counter = new javax.swing.JLabel();
            count_diplay = new javax.swing.JTextField();
            Middle_Center = new javax.swing.JPanel();
            accumulator = new javax.swing.JLabel();
            accumulator_display = new javax.swing.JTextField();
            Middle_East = new javax.swing.JPanel();
            next_Instruction = new javax.swing.JLabel();
            instruction_Display = new javax.swing.JTextField();
            Bottom_West = new javax.swing.JPanel();
            Bottom_East = new javax.swing.JPanel();
            Top_Bottom_East = new javax.swing.JPanel();
            jScrollPane3 = new javax.swing.JScrollPane();
            enter_input = new javax.swing.JTextArea();
            jScrollPane2 = new javax.swing.JScrollPane();
            output_display = new javax.swing.JTextArea();
            Input_Value = new javax.swing.JLabel();
            Output_Value = new javax.swing.JLabel();
            Center_Bottom_East = new javax.swing.JPanel();
            memory_options_one = new javax.swing.JComboBox<>();
            jScrollPane4 = new javax.swing.JScrollPane();
            memory_display_one = new javax.swing.JTextArea();
            Last_Bottom_East = new javax.swing.JPanel();
            memory_options_two = new javax.swing.JComboBox<>();
            jScrollPane5 = new javax.swing.JScrollPane();
            memory_display_two = new javax.swing.JTextArea();
            jScrollPane1 = new javax.swing.JScrollPane();
            input_code_area = new javax.swing.JTextArea();
    
            jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    
            Upper_Panel.setName("Upper_Panel"); // NOI18N
    
            selectFile.setText("Select File");
            selectFile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            selectFile.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
    
                    JFileChooser fileChooser = new JFileChooser();
    
                    // Show the file chooser dialog
                    int returnValue = fileChooser.showOpenDialog(null);
    
                    if (returnValue == JFileChooser.APPROVE_OPTION) {
                        // Get the selected file
                        java.io.File selectedFile = fileChooser.getSelectedFile();
                        System.out.println("Selected file: " + selectedFile.getAbsolutePath());
                        String objectFileName=selectedFile.getAbsolutePath();
                    }
                }
            });
    
            file_Selected.setEditable(false);
            file_Selected.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            file_Selected.setText("file selected");
            file_Selected.setBorder(null);
            file_Selected.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    file_SelectedActionPerformed(evt);
                }
            });
    
            Help.setLabel("Help");
            Help.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    JFrame frame = new JFrame("Help");
                JOptionPane.showMessageDialog(frame,
                                "amb MA HB = Alter contents of the byte at MA to unsigned hex value HB\namd MA SD = Alter contents of the two-byte pair at MA to signed integer value SD\namdx MA HD = Alter contents of the two-byte pair at MA to unsigned hex value HD\nba MA = Set a breakpoint at address MA\nbl L = Set a breakpoint at source-line L\ncb = Clear all breakpoints\nmb = Display all of machine memory as bytes in hex\nmd = Display all of machine memory as 2-byte data in hex\nmi = Display all of machine memory as instructions, data, and labels\nob = Display the portion of machine memory holding object code as bytes in hex\nod = Display the portion of machine memory holding object code as 2-byte data in hex\noi = Display the portion of machine memory holding object code as instructions, data, and labels\nr = Run machine until error occurs or stop instruction is executed\ns = Display machine state (accumulator, program counter, etc.)\nt = Toggle instruction tracing\nz = Reinitialize program counter to zero");
                }
            });
    
            Start.setText("Start");
            Start.setActionCommand("Start");
            Start.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    StartActionPerformed(evt);
                }
            });
    
            Pause.setActionCommand("Pause");
            Pause.setLabel("Pause");
    
            next_Line.setText("Next Line");
    
            executeAgain.setText("Again");
            executeAgain.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    executeAgainActionPerformed(evt);
                }
            });
    
            Stop.setText("Stop");
    
            Save.setText("Save");
            Save.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    SaveActionPerformed(evt);
                }
            });
    
            adjust_Speed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Speed", "Speed x1.5", "Speed x2" }));
    
            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Start)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Pause)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(next_Line)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(executeAgain)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Stop)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(adjust_Speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Save)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Start)
                        .addComponent(Pause)
                        .addComponent(next_Line)
                        .addComponent(executeAgain)
                        .addComponent(Stop)
                        .addComponent(Save)
                        .addComponent(adjust_Speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
    
            javax.swing.GroupLayout Upper_PanelLayout = new javax.swing.GroupLayout(Upper_Panel);
            Upper_Panel.setLayout(Upper_PanelLayout);
            Upper_PanelLayout.setHorizontalGroup(
                Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Upper_PanelLayout.createSequentialGroup()
                    .addGap(0, 166, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(187, 187, 187))
                .addGroup(Upper_PanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(file_Selected, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addComponent(selectFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Help))
            );
            Upper_PanelLayout.setVerticalGroup(
                Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Upper_PanelLayout.createSequentialGroup()
                    .addGroup(Upper_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Upper_PanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(selectFile))
                        .addComponent(Help))
                    .addGap(0, 0, 0)
                    .addComponent(file_Selected, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
    
            file_Selected.getAccessibleContext().setAccessibleParent(selectFile);
    
            Middle_West.setToolTipText("");
            Middle_West.setPreferredSize(new java.awt.Dimension(168, 102));
    
            Program_Counter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            Program_Counter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            Program_Counter.setText("Count");
    
            count_diplay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            count_diplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            count_diplay.setText("###");
            count_diplay.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    count_diplayActionPerformed(evt);
                }
            });
    
            javax.swing.GroupLayout Middle_WestLayout = new javax.swing.GroupLayout(Middle_West);
            Middle_West.setLayout(Middle_WestLayout);
            Middle_WestLayout.setHorizontalGroup(
                Middle_WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Middle_WestLayout.createSequentialGroup()
                    .addContainerGap(55, Short.MAX_VALUE)
                    .addGroup(Middle_WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Program_Counter, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addComponent(count_diplay, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap(55, Short.MAX_VALUE))
            );
            Middle_WestLayout.setVerticalGroup(
                Middle_WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Middle_WestLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(Program_Counter, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(count_diplay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
    
            Middle_Center.setPreferredSize(new java.awt.Dimension(168, 102));
    
            accumulator.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            accumulator.setText("ACC");
            accumulator.setMaximumSize(new java.awt.Dimension(34, 25));
            accumulator.setMinimumSize(new java.awt.Dimension(34, 25));
    
            accumulator_display.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            accumulator_display.setText("###");
    
            javax.swing.GroupLayout Middle_CenterLayout = new javax.swing.GroupLayout(Middle_Center);
            Middle_Center.setLayout(Middle_CenterLayout);
            Middle_CenterLayout.setHorizontalGroup(
                Middle_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Middle_CenterLayout.createSequentialGroup()
                    .addGroup(Middle_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Middle_CenterLayout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(accumulator_display, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Middle_CenterLayout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(accumulator, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(48, Short.MAX_VALUE))
            );
            Middle_CenterLayout.setVerticalGroup(
                Middle_CenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Middle_CenterLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(accumulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(accumulator_display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(43, Short.MAX_VALUE))
            );
    
            next_Instruction.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            next_Instruction.setText("Next Instruction");
    
            instruction_Display.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
            instruction_Display.setText("g#h");
    
            javax.swing.GroupLayout Middle_EastLayout = new javax.swing.GroupLayout(Middle_East);
            Middle_East.setLayout(Middle_EastLayout);
            Middle_EastLayout.setHorizontalGroup(
                Middle_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Middle_EastLayout.createSequentialGroup()
                    .addGroup(Middle_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Middle_EastLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(next_Instruction))
                        .addGroup(Middle_EastLayout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(instruction_Display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(19, Short.MAX_VALUE))
            );
            Middle_EastLayout.setVerticalGroup(
                Middle_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Middle_EastLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(next_Instruction)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(instruction_Display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(43, 43, 43))
            );
    
            javax.swing.GroupLayout Middle_PanelLayout = new javax.swing.GroupLayout(Middle_Panel);
            Middle_Panel.setLayout(Middle_PanelLayout);
            Middle_PanelLayout.setHorizontalGroup(
                Middle_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Middle_PanelLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(Middle_Center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Middle_West, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(161, 161, 161)
                    .addComponent(Middle_East, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(51, 51, 51))
            );
            Middle_PanelLayout.setVerticalGroup(
                Middle_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Middle_PanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(Middle_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Middle_East, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Middle_West, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(Middle_Center, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                    .addContainerGap())
            );
    
            javax.swing.GroupLayout Bottom_WestLayout = new javax.swing.GroupLayout(Bottom_West);
            Bottom_West.setLayout(Bottom_WestLayout);
            Bottom_WestLayout.setHorizontalGroup(
                Bottom_WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 7, Short.MAX_VALUE)
            );
            Bottom_WestLayout.setVerticalGroup(
                Bottom_WestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
    
            jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
    
            enter_input.setColumns(20);
            enter_input.setRows(5);
            jScrollPane3.setViewportView(enter_input);
            enter_input.getAccessibleContext().setAccessibleParent(Bottom_West);
    
            jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
    
            output_display.setColumns(20);
            output_display.setRows(5);
            jScrollPane2.setViewportView(output_display);
    
            Input_Value.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            Input_Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            Input_Value.setText("Input");
            Input_Value.setOpaque(true);
    
            Output_Value.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
            Output_Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            Output_Value.setText("Output");
    
            javax.swing.GroupLayout Top_Bottom_EastLayout = new javax.swing.GroupLayout(Top_Bottom_East);
            Top_Bottom_East.setLayout(Top_Bottom_EastLayout);
            Top_Bottom_EastLayout.setHorizontalGroup(
                Top_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Top_Bottom_EastLayout.createSequentialGroup()
                    .addGroup(Top_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Input_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(Top_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Top_Bottom_EastLayout.createSequentialGroup()
                            .addComponent(Output_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(Top_Bottom_EastLayout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addContainerGap())))
            );
            Top_Bottom_EastLayout.setVerticalGroup(
                Top_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Top_Bottom_EastLayout.createSequentialGroup()
                    .addGroup(Top_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Input_Value)
                        .addComponent(Output_Value))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(Top_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
            );
    
            memory_options_one.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Object code as bytes in Hex", "Object code as 2 byte data in Hex", "Object code as instructions-data and labels", "Edit" }));
            memory_options_one.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    memory_options_oneActionPerformed(evt);
                }
            });
    
            memory_display_one.setColumns(20);
            memory_display_one.setRows(5);
            jScrollPane4.setViewportView(memory_display_one);
    
            javax.swing.GroupLayout Center_Bottom_EastLayout = new javax.swing.GroupLayout(Center_Bottom_East);
            Center_Bottom_East.setLayout(Center_Bottom_EastLayout);
            Center_Bottom_EastLayout.setHorizontalGroup(
                Center_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Center_Bottom_EastLayout.createSequentialGroup()
                    .addGroup(Center_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4)
                        .addComponent(memory_options_one, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            Center_Bottom_EastLayout.setVerticalGroup(
                Center_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Center_Bottom_EastLayout.createSequentialGroup()
                    .addComponent(memory_options_one, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
            );
    
            memory_options_two.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Object code as bytes in Hex", "Object code as 2 byte data in Hex", "Object code as instructions-data and labels", "Edit" }));
            memory_options_two.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    memory_options_twoActionPerformed(evt);
                }
            });
    
            memory_display_two.setColumns(20);
            memory_display_two.setRows(5);
            jScrollPane5.setViewportView(memory_display_two);
    
            javax.swing.GroupLayout Last_Bottom_EastLayout = new javax.swing.GroupLayout(Last_Bottom_East);
            Last_Bottom_East.setLayout(Last_Bottom_EastLayout);
            Last_Bottom_EastLayout.setHorizontalGroup(
                Last_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Last_Bottom_EastLayout.createSequentialGroup()
                    .addGroup(Last_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane5)
                        .addComponent(memory_options_two, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            Last_Bottom_EastLayout.setVerticalGroup(
                Last_Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Last_Bottom_EastLayout.createSequentialGroup()
                    .addComponent(memory_options_two, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
            );
    
            javax.swing.GroupLayout Bottom_EastLayout = new javax.swing.GroupLayout(Bottom_East);
            Bottom_East.setLayout(Bottom_EastLayout);
            Bottom_EastLayout.setHorizontalGroup(
                Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Bottom_EastLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addGroup(Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Top_Bottom_East, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Center_Bottom_East, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Last_Bottom_East, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            );
            Bottom_EastLayout.setVerticalGroup(
                Bottom_EastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Bottom_EastLayout.createSequentialGroup()
                    .addComponent(Top_Bottom_East, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Center_Bottom_East, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Last_Bottom_East, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
    
            input_code_area.setColumns(20);
            input_code_area.setRows(5);
            jScrollPane1.setViewportView(input_code_area);
            input_code_area.getAccessibleContext().setAccessibleParent(Bottom_West);
    
            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Middle_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Bottom_West, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Bottom_East, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Upper_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Upper_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(Middle_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Bottom_West, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(Bottom_East, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
    
            pack();
        }// </editor-fold>//GEN-END:initComponents
    
        private void file_SelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_file_SelectedActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_file_SelectedActionPerformed
    
        private void memory_options_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memory_options_oneActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_memory_options_oneActionPerformed
    
        private void memory_options_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memory_options_twoActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_memory_options_twoActionPerformed
    
        private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_StartActionPerformed
    
        private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_HelpActionPerformed
    
        private void selectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_selectFileActionPerformed
    
        private void executeAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeAgainActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_executeAgainActionPerformed
    
        private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_SaveActionPerformed
    
        private void count_diplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_diplayActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_count_diplayActionPerformed
    
        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(DebugFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(DebugFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(DebugFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(DebugFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
    
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new DebugFrame().setVisible(true);
                }
            });
        }
    
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel Bottom_East;
        private javax.swing.JPanel Bottom_West;
        private javax.swing.JPanel Center_Bottom_East;
        private javax.swing.JButton Help;
        private javax.swing.JLabel Input_Value;
        private javax.swing.JPanel Last_Bottom_East;
        private javax.swing.JPanel Middle_Center;
        private javax.swing.JPanel Middle_East;
        private javax.swing.JPanel Middle_Panel;
        private javax.swing.JPanel Middle_West;
        private javax.swing.JLabel Output_Value;
        private javax.swing.JButton Pause;
        private javax.swing.JLabel Program_Counter;
        private javax.swing.JButton Save;
        private javax.swing.JButton Start;
        private javax.swing.JButton Stop;
        private javax.swing.JPanel Top_Bottom_East;
        private javax.swing.JPanel Upper_Panel;
        private javax.swing.JLabel accumulator;
        private javax.swing.JTextField accumulator_display;
        private javax.swing.JComboBox<String> adjust_Speed;
        private javax.swing.JTextField count_diplay;
        private javax.swing.JTextArea enter_input;
        private javax.swing.JButton executeAgain;
        private javax.swing.JTextField file_Selected;
        private javax.swing.JTextArea input_code_area;
        private javax.swing.JTextField instruction_Display;
        private javax.swing.JComboBox<String> jComboBox3;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JTextArea memory_display_one;
        private javax.swing.JTextArea memory_display_two;
        private javax.swing.JComboBox<String> memory_options_one;
        private javax.swing.JComboBox<String> memory_options_two;
        private javax.swing.JLabel next_Instruction;
        private javax.swing.JButton next_Line;
        private javax.swing.JTextArea output_display;
        private javax.swing.JButton selectFile;
        // End of variables declaration//GEN-END:variables
    }
    
        

        Scanner inputStream = new Scanner(System.in);
        
        VM252Model simulatedMachine = new VM252Model();
        
        simulatedMachine.attach(new AccumulatorPrinter(simulatedMachine));
        simulatedMachine.attach(new ProgramCounterPrinter(simulatedMachine));
        simulatedMachine.attach(new MemoryBytePrinter(simulatedMachine));
        simulatedMachine.attach(new StopAnnouncer(simulatedMachine));

        DemonstrationController simulator = new DemonstrationController(simulatedMachine);

        start.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                        try {
                            simulator.loadAndRun(objectFileName, input.getText() , System.out);
                        } catch (IOException ex) {
                            Logger.getLogger(Demonstration.class.getName()).log(Level.SEVERE, null, ex);
                        }
      
            }
                });
   
           }

}

    
